- CHANGELOG.md
- beaglebone.coffee
- layers/meta-resin-beaglebone/conf/layer.conf
- layers/meta-resin-beaglebone/conf/samples/bblayers.conf.sample
@floion @agherzan
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-beaglebone/1)
> Beaglebone transition to jethro

- .gitmodules
- layers/meta-resin-beaglebone/conf/samples/bblayers.conf.sample
> Switch to docker

- CHANGELOG.md
- beaglebone-green-wifi.coffee
- layers/meta-resin-beaglebone/conf/machine/beaglebone-green-wifi.conf
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0003-am335x_evm.h-Change-default-dtb-for-Beaglebone-Green-Wireless.patch
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
> Bbgw support

- CHANGELOG.md
- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
> Improve build disk usage

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/uEnv.txt_internal
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
- layers/meta-resin-beaglebone/recipes-core/images/resin-image-flasher.bbappend
- layers/meta-resin-beaglebone/recipes-support/resin-init/resin-init-flasher.bbappend
> Update meta-resin submodule and use new flasher strategy

- CHANGELOG.md
- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg
> Replace SUPERVISOR_TAG by TARGET_TAG on resin-beaglebone

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb
@floion @telphan @petrosagg
Connects to resin-os/resin-beaglebone#18
> Compress kmodules

- CHANGELOG.md
- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg
> Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-beaglebone

- CHANGELOG.md
- beaglebone-green.coffee
- layers/meta-resin-beaglebone/conf/machine/beaglebone-green.conf
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0004-am335x_evm.h-Change-default-dtb-for-Beaglebone-Green.patch
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
- layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb
@agherzan @michal-mazurek @telphan @lorenzo-stoakes 
Connect to #28
> Add support for the beaglebone green board

- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
Signed-off-by: Florin Sarbu <florin@resin.io>
> local.conf.sample: Add bbg and bbgw

- .gitmodules
- beaglebone-green-wifi.coffee
- beaglebone-green.coffee
- beaglebone.coffee
Signed-off-by: Eugene Mirotin <eugene@resin.io>
This implements https://github.com/resin-os/resin-yocto-scripts/pull/31, will be updated properly after that PR is merged.
> Simplified JSON manifest build process

- CHANGELOG.md
- beaglebone-green-wifi.coffee
- beaglebone-green.coffee
- beaglebone.coffee
@michal-mazurek @telphan @agherzan
> Switch partition with conf in coffee

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb
@agherzan @michal-mazurek @telphan
> Update kernel to 4.4.20

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb
@agherzan @telphan @michal-mazurek
> Update kernel to 4.4.21

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb
@agherzan @telphan @lorenzo-stoakes @michal-mazurek
> Update kernel to 4.4.21-ti-rt-r46

- CHANGELOG.md
- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
@agherzan @floion 
Connects to resin-os/meta-resin#315
> Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

- CHANGELOG.md
- layers/meta-resin-beaglebone/conf/samples/bblayers.conf.sample
Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek
> Add meta-filesystem as we need aufs-utils on resin-beaglebone

- README.md
Connects to contributing
@telphan @floion @michal-mazurek
> Add Contributing section on resin-beaglebone

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-core/fix-mmc-bbb/files/fix-mmc-bbb.conf
- layers/meta-resin-beaglebone/recipes-core/fix-mmc-bbb/fix-mmc-bbb.bb
- layers/meta-resin-beaglebone/recipes-core/images/resin-image.bbappend
connect https://github.com/resin-os/resinos/issues/88
> Backport the fix_mmc_bbb PR

- CHANGELOG.md
> * Update resin-yocto-scripts to fix logging in container builds on resin-beaglebone

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-core/fix-mmc-bbb/files/fix-mmc-bbb.conf
Connected to resin-os/resinos#162
> [1.X] Reduce page cache pressure during I/O heavy operations

- CHANGELOG.md
- layers/meta-resin-beaglebone/recipes-core/fix-mmc-bbb/files/fix-mmc-bbb.conf
This also brings in the fadvise-enabled docker daemon
Connected to resin-os/resinos#162
> Reduce page cache pressure during I/O heavy operations

- beaglebone-pocket.coffee
- layers/meta-resin-beaglebone/conf/machine/beaglebone-pocket.conf
- layers/meta-resin-beaglebone/conf/samples/local.conf.sample
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0001-Add-support-for-BeagleBoard.org-PocketBeagle.patch
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
- layers/meta-resin-beaglebone/recipes-core/images/resin-image.inc
Added support for Pocket Beagle board
> Added Balena OS support for PocketBeagle board

- beaglebone-pocket.coffee
- layers/meta-resin-beaglebone/recipes-bsp/scripts/boot-scripts.bb
- layers/meta-resin-beaglebone/recipes-bsp/scripts/boot-scripts/0001-Adapted-scripts-for-Balena-usage.patch
- layers/meta-resin-beaglebone/recipes-bsp/scripts/boot-scripts/usb-eth-startup.service
- layers/meta-resin-beaglebone/recipes-core/images/resin-image.bbappend
- Integrated scripts found in vendor provided Debian images
- Removed unnecessary functionality from them
- Added instructions for Linux in coffee file
With these changes only 1 usb eth interface is created.
Connection is stable now and board is accessible in the staging dashboard.
> Integrated scripts for usb network sharing

- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot/am335x_evm-autoboot-zero.patch
- layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot_2018.11.bbappend
- balena-yocto-scripts: Update to v1.0.2
- meta-resin: Update to v2.30.0
- u-boot: Set pocketbeagle autoboot delay to 0
> Set uboot delay to 0

- repo.yml
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
> Fix reference in repo.yml to point to the correct URL

- beagleboard-xm.svg
Chagelog-entry: Add icon for Beagleboard-XM board
Signed-off-by: Sebastian Panceac <sebastian@balena.io>
> Add icon for Beagleboard-XM board

- layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot/beagle-xm--Balena-environment.patch
- layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot_2018.11.bbappend
Changelog-entry: u-boot: Integrate Balena env for Beagleboard-XM
Signed-off-by: Sebastian Panceac <sebastian@balena.io>
> u-boot: Integrate Balena env for Beagleboard-XM

- README.md
Change-type: hotfix 
Changelog-entry: Update directory names in README.md
Signed-off-by: Rafal Sokolowski <sokol-77@wp.pl>
> README.md update to match the directory names

- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0002-NFLX-2019-001-SACK-Panic.patch
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0003-NFLX-2019-001-SACK-Panic-for-lteq-4.14.patch
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0004-NFLX-2019-001-SACK-Slowness.patch
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0005-NFLX-2019-001-Resour-Consump-Low-MSS.patch
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0006-NFLX-2019-001-Resour-Consump-Low-MSS.patch
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend
ID: NFLX-2019-001
Title: Linux and FreeBSD Kernel: Multiple TCP-based remote denial of service vulnerabilities
Release Date: 2019-06-17
Severity: Critical
> Netflix patches

- beagleboard-xm.coffee
- beaglebone-green-wifi.coffee
- beaglebone-green.coffee
- beaglebone-pocket.coffee
- beaglebone.coffee
- layers/meta-balena-beaglebone/conf/layer.conf
- layers/meta-balena-beaglebone/conf/samples/bblayers.conf.sample
- layers/meta-balena-beaglebone/recipes-core/images/resin-image.inc
Update meta-balena from 2.43.0 to 2.44.0
Changelog-entry: Update meta-balena from v2.43.0 to v2.44.0
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
> layers/meta-balena: Update to v2.45.0

- layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot_2018.11.bbappend
- layers/meta-balena-beaglebone/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend
Update meta-balena from 2.45.0 to 2.46.1
Changelog-entry: Update meta-balena from v2.45.0 to v2.46.1
> layers/meta-balena: Update to v2.46.1

- beagleboard-xm.coffee
- beaglebone-green-wifi.coffee
- beaglebone-green.coffee
- beaglebone-pocket.coffee
Change the state field to 'released'
instead of 'experimental'
Changelog-entry: Change the state to 'released' in the coffee file
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
> coffee: Set state to 'released'

- beagleboard-xm.coffee
- beaglebone-green-wifi.coffee
- beaglebone-green.coffee
- beaglebone-pocket.coffee
- beaglebone.coffee
Changelog-entry: Set private to false in .coffee files for the public device types
> .coffee: Set private to false for the public device types

- beaglebone-green-wifi.coffee
Changelog-entry: beaglebone: Remove duplicate instruction for power removal
> beaglebone: Remove duplicate instruction for power removal

- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend
- layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_5.4.bb
Addresses https://github.com/balena-os/balena-beaglebone/issues/253
> linux-beagleboard: Update to 5.4.70-ti-r21, add HM3301
