beaglebone.coffee

This makes the instructions use Etcher as primary image burning software.
To make it work:
1. approve and merge https://github.com/resin-io/resin-device-types/pull/7
2. update the `resin-device-types` submodule in this branch and update this PR
3. test how the JSON file is built (I've tested it myself by checking out the corresponding branch in a submodule)
4. approve and merge this PR
5. follow the standard procedure to release this device type and get it to img-maker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-beaglebone/4)

use etcher instructions

---

beaglebone.coffee

It uses https://github.com/resin-io/resin-device-types/pull/8
What's in this PR:
- we agreed to use the link to the etcher home page instead of the direct download link
- now we don't need os-specific instructions altogether
- I've also demonstrated that as our normal instructions end with post-provisioning instructions we can remove duplication and use the power of real programming language
As with https://github.com/resin-io/resin-device-types/pull/8 I'm going to merge this right now (I've tested the build locally). Again blame me and ping me if you don't like something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-beaglebone/6)

use simplified etcher instructions

---

CHANGELOG.md
layers/meta-resin-beaglebone/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend

Connects to resin-os/meta-resin#133-supervisor-custom-image-tag
@telphan @floion

Custom docker images in connectable builds on resin-beaglebone

---

CHANGELOG.md
layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_4.4.bb

This causes problems if people try to modprobe from within their
containers based on either Debian or Ubuntu.
Connects to https://github.com/resin-os/resinos/issues/89

linux-beaglebone: disable kernel module compression

---

CHANGELOG.md
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0005-Autoboot-keyboard-beaglebone-fixes.patch
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend

connect https://github.com/resin-os/resinos/issues/80

u-boot: only a predefined key can delay or abort boot

---

CHANGELOG.md
layers/meta-resin-beaglebone/recipes-connectivity/bb-wl18xx-wlan0/bb-wl18xx-wlan0.bb
layers/meta-resin-beaglebone/recipes-connectivity/bb-wl18xx-wlan0/files/bb-wl18xx-wlan0
layers/meta-resin-beaglebone/recipes-connectivity/bb-wl18xx-wlan0/files/bb-wl18xx-wlan0.service
layers/meta-resin-beaglebone/recipes-core/images/resin-image.bbappend

This is an attempt to fix https://github.com/resin-os/resinos/issues/133
The MAC address for the wifi interface is stored in the EEPROM and needs to be set at boot, otherwise it remains DE:AD:BE:EF:00:00

Set wifi MAC address based on the contents of the EEPROM

---

CHANGELOG.md
layers/meta-resin-beaglebone/recipes-kernel/linux/bb-org-overlays.bb
layers/meta-resin-beaglebone/recipes-kernel/linux/bb-org-overlays/BB-CAN0-00A0.dts
layers/meta-resin-beaglebone/recipes-kernel/linux/bb-org-overlays/BB-I2C2N-00A0.dts

We add the device tree overlay which does the pinmuxing for using the CAN interface
from P9 pins 19 and 20.
However, the current .dtb we use enables I2C2 on those particular pins so before we
are able to load this overlay we need to also disable I2C2 (by using the BB-I2C2N-00A0 overlay).
First disable I2C2 and then enable CAN0:
Signed-off-by: Florin Sarbu <florin@resin.io>

bb-org-overlays: Add overlays for being able to use CAN0

---

CHANGELOG.md

This brings in a newer rust version which fixes some issues when compiling log crate.

Update meta-rust pyro branch

---

layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0001-Integrate-with-Balena-environment-configuration.patch
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0002-am335x_evm_defconfig-Reduce-SPL-.rodata-size.patch
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend

The BSP layer at the rocko branch has an issue with the boot
stuck in a loop. See details here:
https://lists.yoctoproject.org/pipermail/meta-ti/2018-October
/011363.html
Changelog-entry: Fix boot loop hang when switched to meta-ti rocko

u-boot-ti-staging: Fix SPL boot loop

---

.gitmodules
layers/meta-resin-beaglebone/conf/samples/local.conf.sample

PocketBeagle is a new addition to the supported
devices so we should start using overlayfs as
Docker storage before the images become available
in production.
Changelog-entry: Use overlayfs for PocketBeagle

local.conf.sample: Use overlayfs for PocketBeagle

---

layers/meta-resin-beaglebone/conf/machine/beaglebone-pocket.conf
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging/0001-u-boot-Disable-logging-on-UART0.patch
layers/meta-resin-beaglebone/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend

Switched console from ttyO0 to ttyGS0 over
USB to free up one uart which needs to
be used with other devices
Console will be available on the host as ttyACM0 after the gadget serial module is loaded on device side. Kernel logs will be visible in dmesg.

u-boot: Switch console to usb

---

layers/meta-resin-beaglebone/conf/machine/beaglebone-pocket.conf
layers/meta-resin-beaglebone/recipes-bsp/scripts/boot-scripts/0001-Adapted-scripts-for-Balena-usage.patch
layers/meta-resin-beaglebone/recipes-bsp/scripts/boot-scripts/usb-eth-startup.service

- Switch console back to uart0
* Changes in u-boot are not reverted because the mainline u-boot is now present.
- Update boot-scripts to enable usb0 connection by default at boot
- Update meta-resin to v2.29.2

PocketBeagle changes

---

layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0001-Use-bbbw-dts-from-4.9.patch
layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

Switched back to 4.9.34-ti-r43 version of BBBW dts to fix
bluetooth timeout issue.
Newer versions of this dts from kernel branches 4.14 onwards
share the same issue - bluetooth timeout. This applies to
to dts versions from Official Debian images as well. However
official Debian images use overlays with which the issue is
not present.
Changelog-entry: Fix BT timeout on Beaglebone Black Wireless

am335x-boneblack-wireless.dts: Use version from linux 4.9 branch

---

layers/meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

Current kernel on the beaglebone exhibits the following issue:
https://github.com/balena-os/balena-beaglebone/issues/177
As a workaround for this issue we disable the reboot on kernel
panic config so that the board can provision as expected.
Changelog-entry: Disable reboot on kernel panic as workaround for https://github.com/balena-os/balena-beaglebone/issues/177

linux-beagleboard: Disable reboot on kernel panic

---

.gitmodules

We do this change because we noticed frequent timeouts
in different parts of our build infrastructure when pulling
the poky repository from https://git.yoctoproject.org/git/poky
Changelog-entry: Change the poky submodule to our github mirror

Change poky submodule to use our github hosted mirror

---

layers/meta-balena-beaglebone/recipes-kernel/linux/bb-org-overlays.bb
layers/meta-balena-beaglebone/recipes-kernel/linux/bb-org-overlays/BB-UART4-RTSCTS-00A0.dts

This overlay enables RTS/CTS flow control for UART4
Changelog-entry: bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay
Signed-off-by: Sharvin Shah sharvinshah51@gmail.com

bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay

---

layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0001-card-power-cycle.patch
layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

We need to power cycle the SD card at the initialization sequence
to put it in a reset state. Otherwise, we will encounter this
error that prevents boot:
[    3.042205] mmc0: card never left busy state
[    3.050262] mmc0: error -110 whilst initialising SD card
Signed-off-by: Sebastian Panceac <sebastian@balena.io>

linux-beagleboard: Power cycle SD card at boot on Beagleboard-XM

---

beaglebone-green-wifi.coffee
layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/0002-rtc-omap-Prevent-kernel-panic-and-reboot-on-shutdown.patch
layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

- Fix reboot due to kernel panic on some boards on which the rtc doesn't trigger the pmic to power off the system. This kernel panic occurs also with the latest bb image debian 9.9 2019-08-03 from beagleboard.org
- Update flashing instructions

bbgw: various fixes

---

beaglebone-green-wifi.coffee

According to the upstream documentation, by default
the beaglebone green will load uboot from sd-card, and switch
to emmc if boot button is pressed.
However, this statement is incorrect and the issue
is masked if BalenaOS is already present on the emmc.
With an official debian image on the eMMC, it will be
necessary to power the board while holding down
the USER/BOOT button.
Addresses https://github.com/balena-os/balena-beaglebone/issues/229

Add reported flashing notice for bbgw

---

layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch

This board was using part uuids for booting. Switch to the meta-balena provided fs uuid for root.
Changelog-entry: u-boot: Use meta-balena fs uuids for beaglebones

u-boot: Use meta-balena fs uuids for beaglebones

---

layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard-5.4/0001-Revert-net-ethernet-ti-cpsw-fix-min-eth-packet-size.patch
layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

This reverts commit 9421c90150470512bd5d0fc49eaa108a0b195358 ("net: ethernet: ti: cpsw: fix min eth packet size") from our kernel tree.
The above commit increased the min tx packet size from 60 to 64 bytes. While this fixes VLAN packets forwarding it breaks communication with some industrial PLC devices, which drop those packets as incorrect because of the extra padding added.
Commit d0ff769214e9705573554921c6a8fe491e01fa30 ("HACK: net: ethernet: ti: cpsw: allow to configure min tx packet size") introduces boot time configurability with a module boot parameter "tx_packet_min", which can be adjusted according to the use-case, however we considered that 60 bytes is a better default value.
Changelog-entry: linux-beagleboard: Revert "cpsw: fix min eth packet size"
Signed-off-by: Zahari Petkov …

linux-beagleboard: Revert "cpsw: fix min eth packet size"

---

beagleboard-xm.coffee
beaglebone-green-gateway.coffee
beaglebone-green-wifi.coffee
beaglebone-green.coffee
beaglebone-pocket.coffee
beaglebone.coffee
layers/meta-balena-beaglebone/conf/samples/local.conf.sample
layers/meta-balena-beaglebone/recipes-bsp/beagle-serial/beagle-serial.bb
layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot/0003-resin-specific-env-integration-kconfig_REWORKED.patch
layers/meta-balena-beaglebone/recipes-connectivity/bb-wl18xx-bluetooth/bb-wl18xx-bluetooth.bb
layers/meta-balena-beaglebone/recipes-connectivity/bb-wl18xx-bluetooth/bb-wl18xx-btwl.bb
layers/meta-balena-beaglebone/recipes-connectivity/bb-wl18xx-wlan0/bb-wl18xx-wlan0.bb
layers/meta-balena-beaglebone/recipes-core/fix-mmc-bbb/fix-mmc-bbb.bb
layers/meta-balena-beaglebone/recipes-core/images/balena-image-flasher.bbappend
layers/meta-balena-beaglebone/recipes-core/images/balena-image.bbappend
layers/meta-balena-beaglebone/recipes-core/images/balena-image.inc
layers/meta-balena-beaglebone/recipes-core/images/resin-image-flasher.bbappend
layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_%.bbappend

Rename resin image types to balena and replace RESIN_ env vars
Changelog-entry: Rename resin image types to balena
Signed-off-by: Kyle Harding <kyle@balena.io>

balena-beaglebone: Rename resin image types to balena

---

layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_5.4.bb

Include this overlay so that users of BeagleBone Green Wireless can load
it and use the gpios.
Changelog-entry: Add am335x-bonegreen-wireless-uboot-univ to rootfs for people using gpios on BeagleBone Green Wireless

linux-beagleboard: Add am335x-bonegreen-wireless-uboot-univ to rootfs

---

layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_5.4.bb

Update meta-balena from 2.85.16 to 2.88.17
Changelog-entry: Update meta-balena from v2.85.16 to v2.88.17

Update meta-balena to 2.88.17

---

layers/meta-balena-beaglebone/recipes-core/systemd/systemd_%.bbappend

Removal of audit sockets to disable audit messages should
be done in meta-balena.
Changelog-entry: recipes-core/systemd: Move audit socket removal to meta-balena

recipes-core/systemd: Move audit socket removal to meta-balena

---

layers/meta-balena-beaglebone/conf/samples/bblayers.conf.sample

Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>

bblayers: Modify layer ordering

---

layers/meta-balena-beaglebone/recipes-kernel/linux/linux-beagleboard_5.4.bb

Include this overlay so that users of BeagleBone Black can load it and use the gpios.
Changelog-entry: Add am335x-boneblack-uboot-univ to rootfs for people using gpios on BeagleBone Black
Signed-off-by: Aodhan Murray <aodhan.murray@gmail.com>

linux-beagleboard: Add am335x-boneblack-uboot-univ to rootfs

---

layers/meta-balena-beaglebone/conf/samples/bblayers.conf.sample

Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>

bblayers.conf.sample: add meta-perl

---

beagleboard-xm.coffee

As per the internal thread https://balena.zulipchat.com/#narrow/stream/360838-balena-io.2Fos.2Fdevices/topic/Beagleboard.20XM.20discontinuation/near/381916302
The platform used for this device ype has been deprecated and will no longer be supported in upstream. See https://git.yoctoproject.org/meta-ti/commit/?id=209da2791f911235faaf4104ebf289b0e11d975b
Changelog-entry: beagleboard-xm: Discontinue device

beagleboard-xm: Discontinue device

---

layers/meta-balena-beaglebone/recipes-containers/docker-disk/balena-supervisor.bbappend

We can use the same one as the beaglebone.
Change-type: patch
Changelog-entry: Add path for LED indentification.
Signed-By: Lisandro Pérez Meyer <lperezmeyer@ics.com>

Add path for LED identification

---

layers/meta-balena-beaglebone/recipes-core/images/balena-image-flasher.bbappend
layers/meta-balena-beaglebone/recipes-core/images/balena-image-initramfs.bbappend
layers/meta-balena-beaglebone/recipes-core/images/balena-image.bbappend

The BeagleBone AI-64 requires the vxd-dec-fw package in order to bring in the video decoder firmware. This avoids:
```
img_dec 4300000.video-decoder: Error!! fw binary is not present
```
dmesg message.
Changelog-entry: Add video decodr firmware for the BeagleBone AI64.
Change-type: patch
Signed-By: Lisandro Pérez Meyer <lperezmeyer@ics.com>

Install video decoder's firmware on the BBAI64.

---

layers/meta-balena-beaglebone/recipes-bsp/u-boot/u-boot-bb.org_%.bbappend

UBOOT_KCONFIG_SUPPORT is already enabled when inheriting resin-u-boot, as discussed in
https://github.com/balena-os/balena-beaglebone/pull/662#discussion_r1565590564
Changelog-Entry: u-boot-bb.org: remove uneeded config stanza

u-boot-bb-org: remove unneeded config stanza
